name:                aoc2020
version:             0.1.0.0
github:              "dimitrijer/aoc2020"
license:             BSD3
author:              "Dimitrije Radojević"
maintainer:          "me@dimitrije.website"
copyright:           "2021 Dimitrije Radojević"

extra-source-files:
- README.md

synopsis:            Solutions for AOC2020
description:         Please see the README on GitHub at <https://github.com/dimitrijer/aoc2020#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1
- containers >= 0.6

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020

tests:
  aoc2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    defaults: hspec/hspec@master
